services:
  ha-z2m:
    container_name: ha-z2m
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:2.1.1
    volumes:
      - ${DIR_CONF:-}configuration.yaml:/app/configuration.example.yaml:ro
      - z2m_ha:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_8eec25963c8eed1195238554b96ce6f8-if00-port0:/dev/ttyUSB0
    networks:
      - ha_network
networks:
  ha_network:
    external: true
volumes:
  z2m_ha:
    external: true
